runtime: nodejs12
handlers:
  - url: /static
    secure: always
    redirect_http_response_code: 301
    script: auto
    static_dir: build/static

  - url: /(.*\.(json|ico|js))$
    secure: always
    redirect_http_response_code: 301
    script: auto
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: .*
    secure: always
    redirect_http_response_code: 301
    script: auto
    static_files: build/index.html
    upload: build/index.html