runtime: nodejs12
handlers:
  - url: /static
    secure: always
    redirect_http_response_code: 301
    static_dir: build/static

  - url: /(.*\.(json|ico|js))$
    secure: always
    redirect_http_response_code: 301
    static_files: build/\1
    upload: build/.*\.(json|ico|js)$

  - url: /sitemap.txt
    static_files: sitemap.txt
    upload: sitemap.txt
  
  - url: /robots.txt
    static_files: robots.txt
    upload: robots.txt

  - url: .*
    secure: always
    redirect_http_response_code: 301
    static_files: build/index.html
    upload: build/index.html