runtime: nodejs12
service: backend

instance_class: B1

basic_scaling:
  max_instances: 1
  idle_timeout: 2m

env_variables:
  PORT: 8080

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto